site_name: "Mobility Data Interoperability Principles"
site_url: https://interoperablemobility.org
repo_url: https://github.com/interoperable-mobility/principles
edit_uri: edit/main/docs

nav:
    - Principles: index.md
    - About: about.md
    - Implementation: implementation.md
    - Support: support.md
    - Procurement: procurement.md
    - Resources: resources.md
    - Details: definitions.md

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.png
  features:
    - navigation.expand
    - navigation.tabs
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  analytics:
    provider: google
    property: G-E6EQB94P7M

plugins:
  - search
  - awesome-pages

extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css
  - css/additional.css

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      linenums: true
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_div_format"
  - pymdownx.smartsymbols
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
      toc_depth: 2
  - smarty
  - fontawesome_markdown
  - pymdownx.details
  - pymdownx.snippets
  - abbr
